'use client';
import { useEffect, useState } from 'react';
const statuses=['NEW REQUEST','REQUEST ACCEPTED','TEAM BEING ASSIGNED','TECHNICIAN ASSIGNED','TEAM EN ROUTE','ARRIVED ON SITE','ASSESSMENT IN PROGRESS','MITIGATION STARTED','EQUIPMENT INSTALLED','DRYING / MONITORING','AUTHORIZATION NEEDED','WORK COMPLETED','CLOSED'];
export default function JobBoard({editable=false,clientView=false}){
 const [jobs,setJobs]=useState([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[note,setNote]=useState(''),[visible,setVisible]=useState(true),[damage,setDamage]=useState({damage_amount:'',damage_description:''});
 async function load(){const r=await fetch('/api/emergencies',{cache:'no-store'});const j=await r.json();setJobs(Array.isArray(j)?j:[]);setLoading(false);if(selected){setSelected(j.find(x=>x.id===selected.id)||selected)}}
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 async function patch(id,data){await fetch('/api/emergencies/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});load()}
 async function addUpdate(){if(!note.trim())return;await fetch('/api/emergencies/'+selected.id+'/updates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:note,visible_to_client:visible,created_by:'Service Team'})});setNote('');load()}
 if(loading)return <p>Loading live calls…</p>;
 return <><div className="list">{jobs.map(job=><div className={'job '+(job.status==='NEW REQUEST'?'emergency':'')} key={job.id} onClick={()=>{setSelected(job);setDamage({damage_amount:job.damage_amount||'',damage_description:job.damage_description||''})}}>
  <div className="row"><div><span className={'badge '+(job.status==='NEW REQUEST'?'danger':'')}>{job.status}</span><h3 style={{marginTop:10}}>{job.account_name||'New / Unregistered Emergency'}</h3></div><span className="muted">{new Date(job.created_at).toLocaleString()}</span></div>
  <p><b style={{color:'white'}}>{job.address}</b>{job.unit?` • Unit ${job.unit}`:''}</p><p>{job.phone}{job.note?` • ${job.note}`:''}</p>
  <div className="jobMeta"><span>Source: <b>{job.source==='client_portal'?'Client Portal':'Public Emergency'}</b></span>{job.damage_amount&&<span>Damage: <b>${Number(job.damage_amount).toLocaleString()}</b></span>}</div>
  {editable&&<div className="grid2" onClick={e=>e.stopPropagation()}><select value={job.status} onChange={e=>patch(job.id,{status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="primaryBtn" onClick={()=>patch(job.id,{status:'REQUEST ACCEPTED',accepted_by:'Service Manager'})}>Accept Emergency</button></div>}
 </div>)}</div>
 {selected&&<div className="modalBackdrop"><div className="modal wideModal"><div className="row"><div><div className="eyebrow">SERVICE CALL #{selected.id.slice(0,8).toUpperCase()}</div><h2>{selected.account_name||'Emergency Service Request'}</h2></div><button className="smallBtn" onClick={()=>setSelected(null)}>Close</button></div>
   <div className="detailGrid"><div className="detailBox"><label>Property</label><b>{selected.address}</b></div><div className="detailBox"><label>Contact</label><b>{selected.phone}</b></div><div className="detailBox"><label>Unit</label><b>{selected.unit||'—'}</b></div><div className="detailBox"><label>Status</label><b>{selected.status}</b></div></div>
   {editable&&<><h3 className="sectionTitle">Damage & Job Information</h3><div className="grid2"><div className="field"><label>Estimated Damage Amount</label><input type="number" value={damage.damage_amount} onChange={e=>setDamage({...damage,damage_amount:e.target.value})}/></div><div className="field"><label>Current Status</label><select value={selected.status} onChange={e=>patch(selected.id,{status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div></div><div className="field"><label>Damage Description</label><textarea value={damage.damage_description} onChange={e=>setDamage({...damage,damage_description:e.target.value})} placeholder="Describe source, affected rooms, visible damage, actions taken..."/></div><button className="smallBtn" onClick={()=>patch(selected.id,damage)}>Save Damage Details</button>
   <h3 className="sectionTitle">Add Service Update</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Team arrived, source stopped, extraction started..."/><div className="row"><label className="check"><input type="checkbox" checked={visible} onChange={e=>setVisible(e.target.checked)}/> Client visible</label><button className="primaryBtn" onClick={addUpdate}>Post Update</button></div></>}
   <h3 className="sectionTitle">Timeline</h3><div className="timeline">{(selected.updates||[]).filter(u=>!clientView||u.visible_to_client).map((u,i)=><div className="timelineItem" key={u.id||i}><div>{u.message}</div><small>{u.visible_to_client?'Client visible':'Internal only'} • {new Date(u.created_at).toLocaleString()}</small></div>)}{!(selected.updates||[]).length&&<p>No updates yet.</p>}</div>
 </div></div>}
 </>
}