const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL;const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY;
let emergencies=[{id:'demo-001',account_name:'Lakeview Property Management',address:'123 Main Street, Mission Viejo, CA',phone:'(949) 555-0199',unit:'204',note:'Active water leak from water heater',source:'client_portal',status:'TEAM EN ROUTE',created_at:new Date().toISOString(),accepted_by:'Demo Service Manager',damage_amount:8500,damage_description:'Water heater leak affecting Unit 204 and ceiling below.',updates:[{id:'u1',message:'Emergency request received.',visible_to_client:true,created_at:new Date().toISOString()},{id:'u2',message:'Technician assigned and team is en route.',visible_to_client:true,created_at:new Date().toISOString()}]}];
let accounts=[{id:'acct-001',name:'Lakeview Property Management',property_name:'Lakeview Apartments',address:'123 Main Street, Mission Viejo, CA',manager_name:'Jane Smith',phone:'(949) 555-0199',email:'manager@example.com',units:164,stage:'ACTIVE ACCOUNT',account_owner:'Daniel',jobs_count:14,revenue:68450,created_at:new Date().toISOString()},{id:'acct-002',name:'Pacific Crest Management',property_name:'Canyon Terrace',address:'26800 Example Rd, Mission Viejo, CA',manager_name:'Michael Torres',phone:'(949) 555-0142',email:'',units:96,stage:'APPOINTMENT SET',account_owner:'Daniel',jobs_count:0,revenue:0,created_at:new Date().toISOString()}];
function headers(){return{apikey:serviceKey,Authorization:`Bearer ${serviceKey}`,'Content-Type':'application/json',Prefer:'return=representation'}}
async function rest(path,options={}){const res=await fetch(`${supabaseUrl}/rest/v1/${path}`,{...options,headers:{...headers(),...(options.headers||{})},cache:'no-store'});if(!res.ok)throw new Error(await res.text());return res.status===204?null:res.json()}
export async function listEmergencies(){if(!supabaseUrl||!serviceKey)return emergencies;const rows=await rest('emergencies?select=*,job_updates(*)&order=created_at.desc');return rows.map(x=>({...x,updates:x.job_updates||[]}))}
export async function createEmergency(data){const record={account_name:data.account_name||null,address:data.address,phone:data.phone,unit:data.unit||null,note:data.note||null,source:data.source||'public',status:'NEW REQUEST'};if(!supabaseUrl||!serviceKey){const item={id:crypto.randomUUID(),...record,created_at:new Date().toISOString(),updates:[]};emergencies=[item,...emergencies];return item}return(await rest('emergencies',{method:'POST',body:JSON.stringify(record)}))[0]}
export async function updateEmergency(id,data){if(!supabaseUrl||!serviceKey){emergencies=emergencies.map(x=>x.id===id?{...x,...data}:x);return emergencies.find(x=>x.id===id)}return(await rest(`emergencies?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(data)}))[0]}
export async function addJobUpdate(id,data){const row={message:data.message,visible_to_client:data.visible_to_client!==false,created_by:data.created_by||'RESTOTECH',created_at:new Date().toISOString()};if(!supabaseUrl||!serviceKey){emergencies=emergencies.map(x=>x.id===id?{...x,updates:[...(x.updates||[]),{id:crypto.randomUUID(),...row}]}:x);return row}return(await rest('job_updates',{method:'POST',body:JSON.stringify({...row,emergency_id:id})}))[0]}
export async function listAccounts(){if(!supabaseUrl||!serviceKey)return accounts;return rest('accounts?select=*&order=created_at.desc')}
export async function createAccount(data){const record={name:data.name,property_name:data.property_name||null,address:data.address||null,manager_name:data.manager_name||null,phone:data.phone||null,email:data.email||null,units:data.units?Number(data.units):null,stage:data.stage||'NEW PROSPECT',account_owner:data.account_owner||null,jobs_count:0,revenue:0};if(!supabaseUrl||!serviceKey){const item={id:crypto.randomUUID(),...record,created_at:new Date().toISOString()};accounts=[item,...accounts];return item}return(await rest('accounts',{method:'POST',body:JSON.stringify(record)}))[0]}
export async function updateAccount(id,data){if(!supabaseUrl||!serviceKey){accounts=accounts.map(x=>x.id===id?{...x,...data}:x);return accounts.find(x=>x.id===id)}return(await rest(`accounts?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(data)}))[0]}
